name: e2e

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

# 👇 Pull the secret into env once
env:
  E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}

jobs:
  mocked:
    name: Playwright (mocked)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

  live:
    name: Playwright (live)
    # 👇 Use env.* (not secrets.*) in conditions
    if: ${{ env.E2E_BASE_URL != '' }}
    needs: mocked
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run live E2E
        env:
          E2E_LIVE: '1'
          # 👇 Pass the env value into the step
          E2E_BASE_URL: ${{ env.E2E_BASE_URL }}
        run: npm run test:e2e
      - name: Upload HTML report (live)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-live
          path: playwright-report
          retention-days: 7
